### ISSUE TITLE
Improve enemy movement

### ISSUE THREAD

**Issue by ianvernon** [ucsb-cs56-projects/cs56-games-pacman#14]
Enemies appear to cluster. Improve their AI by having them follow Pacman (preferably at different speeds so the game isn't too difficult). 
~estimated 250 points

**Comment by 2yangk23** [comment]
Pathfinding for ghosts is complete.  See Ghost.java and Node.java

**Comment by jimzhu1993** [comment]
Implement ghosts called speedy, bashful, and pokey. Rightnow, we have shadow only.
detail : http://gameinternals.com/post/2072558330/understanding-pac-man-ghost-behavior
~ 200 points for each ghost

**Comment by mliou** [comment]
Approved.
