### ISSUE TITLE
Refactor Leaderboard + LeaderboardGUI interaction

### ISSUE THREAD

**Issue by katfom** [UCSB-CS56-Projects/cs56-games-pacman#17]
Currently there are working Leaderboard and LeaderboardGui classes, however the LeaderboardGUI contains an instance of Leaderboard. Ideally the Leaderboard would contain a instance of LeaderboardGUI to allow for multiple views/presentations of Leaderboard (if for instance there were multiple GUI classes). Also, possibly change how the getPlayerTopThree() and getTopThree() methods in Leaderboard.java work to make them more efficient. (Perhaps use sorting).
~150 points

**Comment by 2yangk23** [comment]
Leaderboard is auto sorted, requesting ~50 points
