### ISSUE TITLE
Create Map Data Structure

### ISSUE THREAD

**Issue by 2yangk23** [UCSB-CS56-Projects/cs56-games-pacman#23]
Create a map data structure, which can be serializable, so it can be saved to file. Also create a map editor so that maps can be easily edited. Finally, refactor code base to implement map data instead of reading from hard-coded arrays. Map data could also include spawn point of pacman and ghost data.

~200 points

**Comment by mliou** [comment]
Approved.

**Comment by ryantse** [comment]
Completed serializable level data. Per commit f6f8ee1ac8a8e2b16022a5f02731fdf43d879ae2.

**Comment by ryantse** [comment]
@hannavigil

**Comment by hannavigil** [comment]
See #42
