### ISSUE TITLE
Integrate Leaderboard and Game Window

### ISSUE THREAD

**Issue by 2yangk23** [ucsb-cs56-projects/cs56-games-pacman#24]
Integrate the leaderboard and game window so that there is only a single window.  Help window could also be integrated.

~100 points

**Comment by 2yangk23** [comment]
Help window is integrated, but leaderboard is not.  See Board.java

**Comment by mliou** [comment]
Approved.

**Comment by zhanchengqian** [comment]
F16 OK

**Comment by rhelmot** [comment]
Leaderboard is also integrated. Idk if this was referring to the "input your name" window, but honesty that's better as a separate window because it requires a text input.
