### ISSUE TITLE
Ghost AI Bug

### ISSUE THREAD

**Issue by 2yangk23** [UCSB-CS56-Projects/cs56-games-pacman#25]
When playing co-op mode, the ghosts only chase Mr. Pacman. If Mr. Pacman dies, all the ghosts chase after the area where he spawns.
When ghost is close to pacman and he goes through a tunnel it will go crazy.

~100 points

**Comment by 2yangk23** [comment]
Ghost AI bugs are all fixed. See Ghost.java

**Comment by mliou** [comment]
Approved.
