### ISSUE TITLE
Create Tunnels

### ISSUE THREAD

**Issue by 2yangk23** [UCSB-CS56-Projects/cs56-games-pacman#26]
Create tunnels that allow you to go across the map. (i.e. when you go into a tunnel at the right side of map, you come out of the left side of the map) Could even make this so that tunnels can move you anywhere on the map.

Ghosts and Pacman should both be allowed to use tunnels.

~200 points

**Comment by 2yangk23** [comment]
Tunnels have been created, and all resulting bugs have been fixed.  See Character.java, Ghost.java, PacPlayer.java, Node.java

**Comment by mliou** [comment]
Approved.
