### ISSUE TITLE
Collision bug

### ISSUE THREAD

**Issue by 2yangk23** [UCSB-CS56-Projects/cs56-games-pacman#28]
If pacman and a ghost both go into a tunnel from different sides at the same time, it is possible for them to pass each other and not collide.  Collision needs to be improved in general. It isn't very sensitive, and the pacman can actually partially overlap the ghosts without colliding.

~100 points

**Comment by 2yangk23** [comment]
Collision needs to be improved in general.  It isn't very sensitive, and the pacman can actually partially overlap the ghosts without colliding.

**Comment by 2yangk23** [comment]
Collision has been improved.  Tunnel glitch is still possible, but very hard to execute.  See Grid.java

**Comment by mliou** [comment]
Approved.
