### ISSUE TITLE
Versus Mode

### ISSUE THREAD

**Issue by jimzhu1993** [UCSB-CS56-Projects/cs56-games-pacman#30]
1. Collision Priority
In Versus mode, if the ghost is stepping on the pellet, pacman will never have the chance to eat it, because the collision between ghost and pacman happens first and then the collision between the pellet and pacman.
~100 points
2. Pop up option so that the ghost that is controlled by number pad could be instead by AI.
~100 points

**Comment by mliou** [comment]
Approved.
