### ISSUE TITLE
New Ghosts

### ISSUE THREAD

**Issue by jimzhu1993** [UCSB-CS56-Projects/cs56-games-pacman#31]
Implement ghosts called speedy, bashful, and pokey. Rightnow, we have shadow only.
detail : http://gameinternals.com/post/2072558330/understanding-pac-man-ghost-behavior
~ 200 points for each ghost

**Comment by mliou** [comment]
Approved.

**Comment by zhanchengqian** [comment]
F16 OK (100 pts for each ghost)

**Comment by natashalee** [comment]
new issue #70
