### ISSUE TITLE
Add music/sound effects

### ISSUE THREAD

**Issue by mliou** [UCSB-CS56-Projects/cs56-games-pacman#32]
Would be awesome if you used the music/sound effects from the original game.
~200 pts

**Comment by beserchris** [comment]
request for more points ~500 due to the complexity required play sounds in quick sequence or simultaneously. (wrote a new Audio class to handle the loading and playing of asset audio files)

**Comment by ryantse** [comment]
CC: @hannavigil

**Comment by hannavigil** [comment]
More points for writing audio class is approved because of difficulty of playing sounds in quick sequence/simultaneously, but not the full 500.
New estimation: ~350 points
