### ISSUE TITLE
Broken level data logic

### ISSUE THREAD

**Issue by ryantse** [UCSB-CS56-Projects/cs56-games-pacman#38]
Currently, the code does not allow for the access of levels 3+ even though the data currently exists. We would like to revamp the level loading data logic. We would like to request a point value assignment to this issue.

**Comment by ryantse** [comment]
CC: @hannavigil

**Comment by hannavigil** [comment]
Estimated ~100

**Comment by beserchris** [comment]
fixed see 75b319e8c6528278c914966cb96636f5f9eb1064 and 21149e316f91ddf9a374003d150fb6baf95acc11
