### ISSUE TITLE
Complete PacMan Level Editor

### ISSUE THREAD

**Issue by ryantse** [UCSB-CS56-Projects/cs56-games-pacman#42]
Add ability to modify existing levels and create new levels with the level editor.

**Comment by ryantse** [comment]
Requested Point Value: 600 pts.
Commit: f6f8ee1ac8a8e2b16022a5f02731fdf43d879ae2
To test the level editor:
````
$ ant run-editor
````
Open file in assets/levels/level*.data

CC: @hannavigil

**Comment by ryantse** [comment]
Updated: cfbce9bf6d586d06b8cc49ba0fed0c3e8670fba2
Fixes an issue with the editor's window state.

**Comment by hannavigil** [comment]
Edit: Estimated ~475 points

**Comment by hannavigil** [comment]
Approved
