### ISSUE TITLE
Feature: Add Pacman Music

### ISSUE THREAD

**Issue by natashalee** [ucsb-cs56-projects/cs56-games-pacman#57]
Add the original pacman theme music! 

estimated points 200

**Comment by rhelmot** [comment]
W18OK 100 points

**Comment by rhelmot** [comment]
...hold up, my computer was just muted. there's already music that plays on startup, and there was no music during gameplay in the original arcade game, except for the annoying WOKKA WOKKA WOKKA sound effect
