### ISSUE TITLE
Developer Mode

### ISSUE THREAD

**Issue by lleeoochen** [UCSB-CS56-Projects/cs56-games-pacman#63]
Have developer mode for custom testing of game players.

1. Invincible Pacman
2. Level skipper
3. Logging information on console (Maybe on another JFrame)
4. A set of keys (switches) for debugging (make ghost edible, re-spawn all ghosts, slow down all character speed)
5. more..

Suggested points: 300

**Comment by natashalee** [comment]
Pull request: https://github.com/UCSB-CS56-Projects/cs56-games-pacman/pull/68. 300 points, closing.
