### ISSUE TITLE
Finish Game After Completing All Levels

### ISSUE THREAD

**Issue by lleeoochen** [ucsb-cs56-projects/cs56-games-pacman#69]
Description:
- The player should be able to actually "win" a game after completing all existing levels with a winning screen. Currently, we are just looping through levels endlessly.

Place to Fix: 
- playGame() method in Board.java

Suggested Points: 
- 150

**Comment by natashalee** [comment]
F17OK 150 points

**Comment by rhelmot** [comment]
superceded by #41
