### ISSUE TITLE
Add Other Ghost Types

### ISSUE THREAD

**Issue by lleeoochen** [ucsb-cs56-projects/cs56-games-pacman#70]
Description:
- Currently, we only have red and pink ghosts. Please add the rest of the ghost types with their corresponding abilities.

Place to fix:
- Ghost.java
- Board.java (maybe)

Suggested points:
- 250

**Comment by natashalee** [comment]
F17OK 250 points

**Comment by rhelmot** [comment]
W18OK 200 points
