### ISSUE TITLE
Allow buffering inputs

### ISSUE THREAD

**Issue by rhelmot** [ucsb-cs56-projects/cs56-games-pacman#74]
One of the things that makes the original game easier to play is that you just have to press once in the direction you want to turn, and then the next time pacman reaches an intersection that allows him to turn in that direction, he will turn. This is called "buffering" an input, since you provide it and then the next time it is applicable it will be applied.

**Comment by rhelmot** [comment]
W18 OK 150 points

**Comment by Aregluss** [comment]
Fixed
