### ISSUE TITLE
Power up items 

### ISSUE THREAD

**Issue by leifdreizler** [UCSB-CS56-Projects/cs56-games-pacman#8]
~depends #12 

Add the "power pills" from the original pacman game that allow the pacman player to capture the ghosts for points.    The ghosts then have to reemerge at some point, after a time delay.

If I recall correctly, the power pill works for some period of time, and the ghosts give you 100 points, 200 points, 300 points, 400 points respectively.      You have to figure out issues like what happens if you eat a second power pill while a current power pill is in effect----does it reset the clock, or add extra time (are the times cumulative?)    And how soon do the ghosts regenerate in that case? 

And does this apply to every mode of play?    Are there issues for the single player, vs. cooperative, vs. "versus" mode?

~estimated 500

On top of this, you could have random items spawn (like in the original game) that give you extra points whenever you pick them up, but does not affect the game play. 

~estimated 300

**Comment by mliou** [comment]
On top of this, you could have random items spawn (like in the original game) that give you extra points whenever you pick them up. 

~estimated 300

**Comment by jimzhu1993** [comment]
Done with the half of the issue:  spawn fruit randomly. See Grid.java Pacplayer.java

**Comment by zhanchengqian** [comment]
F16 OK (500pts changed to 200pts, 300pts changed to 100pts)
